### ISSUE TITLE
Disappointed with Unprofessional Behavior in Hiring

### ISSUE THREAD

**Issue by Platonicdragon** [StarLight-Oliver/Lua-Snippets#1]
I must express my extreme disappointment and frustration with your unprofessional behavior. It is unacceptable that after we reached an agreement, you disappeared without any notice. Despite my attempts to contact you for over two months, you only responded with a single apologetic message on Steam.

And when I requested a written confirmation of your commitment, you chose to block all communications instead. This behavior is simply incomprehensible and unprofessional. I have never encountered such an uncooperative individual before.

Furthermore, it has come to my attention that you have been banned from Gmodstore for "Leaking / Not paying back upfront payment for uncompleted job." https://www.gmodstore.com/users/crazynator
This information only adds to my disappointment and frustration.

I expect better from professionals, and your actions have fallen far short of that expectation.

My only wish is to hear what you have to say for yourself, and the reasoning behind such actions.

**Comment by StarLight-Oliver** [comment]
Hi dude, you appear to have gotten the wrong person.
This is my steam account: https://steamcommunity.com/id/no1stargeorge/

**Comment by StarLight-Oliver** [comment]
I have little to no relation with Crazynator, other than previously working together briefly on a project.
If you reach out to me at that steam link I am happy to see if I am able to help you with your issue. But I am not the same dev. And I would like to know what has prompted you to believe we are the same person.
